import { ProjectBrandGuide, EmailSection, EmailElement } from "./email.types"

export const mockBrandGuide: ProjectBrandGuide = {
    headingFontFamily: "Georgia, serif",
    paragraphFontFamily: "Arial, sans-serif",

    primary: "#3b82f6",
    primaryForeground: "#ffffff",

    secondary: "#6366f1",
    secondaryForeground: "#ffffff",

    accent: "#8b5cf6",
    accentForeground: "#ffffff",

    muted: "#f1f5f9",
    mutedForeground: "#64748b",

    danger: "#ef4444",
    dangerForeground: "#ffffff",

    warning: "#f59e0b",
    warningForeground: "#ffffff",

    success: "#10b981",
    successForeground: "#ffffff",

    info: "#06b6d4",
    infoForeground: "#ffffff",

    background: "#ffffff",
    foreground: "#0f172a",
}

export const mockEmailSections: EmailSection[] = [
    {
        id: "section-1",
        index: 0,
        styles: {
            "background-color": mockBrandGuide.primary,
            "padding": "40px 20px",
            "text-align": "center",
        },
    },
    {
        id: "section-2",
        index: 1,
        styles: {
            "background-color": mockBrandGuide.background,
            "padding": "40px 20px",
        },
    },
    {
        id: "section-3",
        index: 2,
        styles: {
            "background-color": mockBrandGuide.muted,
            "padding": "30px 20px",
        },
    },
    {
        id: "section-4",
        index: 3,
        styles: {
            "background-color": mockBrandGuide.background,
            "padding": "40px 20px",
            "text-align": "center",
        },
    },
    {
        id: "section-5",
        index: 4,
        styles: {
            "background-color": mockBrandGuide.foreground,
            "padding": "30px 20px",
            "text-align": "center",
        },
    },
]

export const mockEmailElements: EmailElement[] = [
    {
        id: "elem-1",
        index: 0,
        type: "text",
        textContent: "Welcome to Our Newsletter",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-1",
        styles: {
            "font-size": "32px",
            "font-weight": "bold",
            "color": mockBrandGuide.primaryForeground,
            "margin": "0",
            "font-family": mockBrandGuide.headingFontFamily,
        },
    },
    {
        id: "elem-2",
        index: 1,
        type: "text",
        textContent: "Stay updated with our latest news and offers",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-1",
        styles: {
            "font-size": "16px",
            "color": mockBrandGuide.primaryForeground,
            "margin": "10px 0 0 0",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
    {
        id: "elem-3",
        index: 0,
        type: "text",
        textContent: "Hello there!",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-2",
        styles: {
            "font-size": "24px",
            "font-weight": "bold",
            "color": mockBrandGuide.foreground,
            "margin": "0 0 20px 0",
            "font-family": mockBrandGuide.headingFontFamily,
        },
    },
    {
        id: "elem-4",
        index: 1,
        type: "text",
        textContent: "We're excited to share some amazing updates with you. Our team has been working hard to bring you new features and improvements that will make your experience even better.",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-2",
        styles: {
            "font-size": "16px",
            "color": mockBrandGuide.foreground,
            "line-height": "1.6",
            "margin": "0 0 20px 0",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
    {
        id: "elem-5",
        index: 2,
        type: "divider",
        textContent: null,
        src: null,
        href: null,
        altText: null,
        sectionId: "section-2",
        styles: {
            "height": "2px",
            "background-color": mockBrandGuide.muted,
            "margin": "20px 0",
        },
    },
    {
        id: "elem-6",
        index: 3,
        type: "text",
        textContent: "Here's what's new:",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-2",
        styles: {
            "font-size": "20px",
            "font-weight": "bold",
            "color": mockBrandGuide.foreground,
            "margin": "0 0 15px 0",
            "font-family": mockBrandGuide.headingFontFamily,
        },
    },
    {
        id: "elem-7",
        index: 4,
        type: "text",
        textContent: "✓ Enhanced performance and speed<br>✓ New intuitive dashboard design<br>✓ Advanced analytics features<br>✓ Mobile app improvements",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-2",
        styles: {
            "font-size": "16px",
            "color": mockBrandGuide.foreground,
            "line-height": "2",
            "margin": "0 0 20px 0",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
    {
        id: "elem-8",
        index: 0,
        type: "text",
        textContent: "Special Offer Inside!",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-3",
        styles: {
            "font-size": "22px",
            "font-weight": "bold",
            "color": mockBrandGuide.foreground,
            "text-align": "center",
            "margin": "0 0 15px 0",
            "font-family": mockBrandGuide.headingFontFamily,
        },
    },
    {
        id: "elem-9",
        index: 1,
        type: "text",
        textContent: "Get 20% off your next purchase when you use code WELCOME20 at checkout. Offer valid for the next 7 days!",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-3",
        styles: {
            "font-size": "16px",
            "color": mockBrandGuide.foreground,
            "text-align": "center",
            "line-height": "1.6",
            "margin": "0",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
    {
        id: "elem-10",
        index: 0,
        type: "link",
        textContent: "Get Started Now",
        src: null,
        href: "#",
        altText: null,
        sectionId: "section-4",
        styles: {
            "display": "inline-block",
            "background-color": mockBrandGuide.primary,
            "color": mockBrandGuide.primaryForeground,
            "padding": "15px 40px",
            "text-decoration": "none",
            "border-radius": "5px",
            "font-size": "16px",
            "font-weight": "bold",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
    {
        id: "elem-11",
        index: 1,
        type: "spacer",
        textContent: null,
        src: null,
        href: null,
        altText: null,
        sectionId: "section-4",
        styles: {
            "height": "20px",
        },
    },
    {
        id: "elem-12",
        index: 2,
        type: "text",
        textContent: "Questions? We're here to help!",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-4",
        styles: {
            "font-size": "14px",
            "color": mockBrandGuide.mutedForeground,
            "margin": "0",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
    {
        id: "elem-13",
        index: 0,
        type: "text",
        textContent: "© 2025 Your Company. All rights reserved.",
        src: null,
        href: null,
        altText: null,
        sectionId: "section-5",
        styles: {
            "font-size": "12px",
            "color": mockBrandGuide.muted,
            "margin": "0 0 10px 0",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
    {
        id: "elem-14",
        index: 1,
        type: "link",
        textContent: "Unsubscribe",
        src: null,
        href: "#",
        altText: null,
        sectionId: "section-5",
        styles: {
            "font-size": "12px",
            "color": mockBrandGuide.muted,
            "text-decoration": "underline",
            "font-family": mockBrandGuide.paragraphFontFamily,
        },
    },
]
